# Generated by Django 5.1.5 on 2025-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
