# Generated by Django 5.2 on 2025-05-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lancamentocaixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
