# Generated by Django 5.2 on 2025-05-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ordemdeservico_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='competencia',
            field=models.CharField(max_length=6),
        ),
        migrations.CreateModel(
            name='FaturaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='core.fatura')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordemdeservico')),
            ],
        ),
    ]
