# Generated by Django 5.2 on 2025-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fatura_competencia_faturaordemservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='ordem_servico',
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
