# Generated by Django 5.2 on 2025-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_fatura_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='competencia',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
