# Generated by Django 5.2 on 2025-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fatura_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='operador',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
