# Generated by Django 5.2 on 2025-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ordemdeservico_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
