# Generated by Django 5.2 on 2025-05-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=20, null=True),
        ),
    ]
