# Generated by Django 5.2 on 2025-05-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_caixa_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocaixa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=10, null=True),
        ),
    ]
