# Generated by Django 5.2.1 on 2025-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lancamentocaixa_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('debito', 'Débito'), ('credito', 'Crédito')], default='', max_length=20, null=True),
        ),
    ]
