# Generated by Django 5.2.1 on 2025-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fatura_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
